Fix certbot reload
elan-ev/opencast_certbot pull request #6
Opened 2023-08-10 11:02 UTC by wsmirnow

Renew service should not be limited on one domain

Certbot take care of all registred certificates by default. We should make use of it and not override this behaviour.

This PR is based on #4 and should be merged in order. It also fixes #2.

2025-01-09 20:55 UTC, lkiesow commented
Conflicts + linting failed.
Can you rebase this?

2025-01-10 08:34 UTC, wsmirnow commented
Is fixed now. Please give it a try.

2025-01-10 08:57 UTC, wsmirnow commented
closes #2

2025-01-19 10:58 UTC, lkiesow requested changes

2025-01-19 10:58 UTC, lkiesow commented on tasks/main.yml
> +# You can remove this task on later versions.
Great. I wanted to fix this forever :+1:

2025-03-06 14:27 UTC, wsmirnow commented on tasks/main.yml
> +# You can remove this task on later versions.
:)

2025-03-21 15:29 UTC, merged